### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Roseghost**
Signed-off-by: Monsterfox <Rosalieswarte@gmail.com>

### Describe the background of your pull request

Update to V 5.5.0 + Add security in config due to update

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Comment by techsmyth** [comment]
Nice to see this seems to have been smooth...no surprises?
Any new functionality to be aware of?

**Comment by Roseghost** [comment]
> Nice to see this seems to have been smooth...no surprises? Any new functionality to be aware of?

Added options such as breadcrumb and navbar disappear on scroll been added 
You can add content based on folders instead of page type 

Only conflicting things we gotta keep in check are : rename any Params.header to Params.banner and with contact widget a certain part has to be moved to the front of the widget so I will have to check. Seeing we do use a contact form soo.. i'll have to fix that now that I'm aware of it.. oops. :) 

But theres a new slider so hopefully I can get that responsive!

**Comment by Roseghost** [comment]
> Nice to see this seems to have been smooth...no surprises? Any new functionality to be aware of?

Contact form seemed to be formed without contact Widget. According to the paragraph "Breaking Changes" we should be fine. Feels kinda suspicious when an update doesn't break anything.

**Comment by techsmyth** [comment]
@Roseghost thanks for comments. Looks like this is ready to go - but do need the CLA signed. Can you please do that? Should only be a simple click through...

**Comment by Roseghost** [comment]
> @Roseghost thanks for comments. Looks like this is ready to go - but do need the CLA signed. Can you please do that? Should only be a simple click through...

Sorry, didn't notice it before. Signed now :)

**Review by techsmyth — APPROVED** [review]

**Pull request merged**
