### PR TITLE
Update Photos + team change

### PR DESCRIPTION
**Pull request by Roseghost**
Hyotte to Past Contributers and Senna added to the team, welcome!

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Comment by Roseghost** [comment]
@BirgitAlkemio  Is het express dat de foto's niet gecentreerd zijn of wil je dit juist wel?

**Comment by BirgitAlkemio** [comment]
@Roseghost Even bellen?

**Comment by Roseghost** [comment]
Still lacking new pictures from Me, Kaylee and possible Lazar

**Review by BirgitAlkemio — CHANGES_REQUESTED** [review]
@Roseghost I think Valentin needs to be in the first row, where Evgeni now is. If we want the steering org first:
Rene, Neil, Fintan, Valentin, Merijn 
The second row:
Evgeni, Denise, etc... on A-Z's last name

@renehonig We converted the bg of the images to neutral. 
All team members with new pictures have responded to my request for their consent except Andrew. Awaiting his response before merging.

**Comment by Roseghost** [comment]
> @Roseghost I think Valentin needs to be in the first row, where Evgeni now is. If we want the steering org first: Rene, Neil, Fintan, Valentin, Merijn The second row: Evgeni, Denise, etc... on A-Z's last name
> 

My bad! they are on alphabet with last names but I accidentally changed Valentin while doing so

**Comment by BirgitAlkemio** [comment]
@Roseghost can you add the GitHub link https://github.com/ccanos
for Carlos?

**Comment by techsmyth** [comment]
@Roseghost @BirgitAlkemio the order should be in time: when they engaged with Alkemio. It should not be based on what their position is - if needed we can cover that separately...

**Comment by BirgitAlkemio** [comment]
@techsmyth Yes this order is covered in the pitchdeck, and was debated/reviewed couple of times. Would make sense having the most prominent teammembers on top. 

Not occurred (to me) the previous order was historical.

As we are growing we could also consider it to be grouped in: 
Operations
Product
Development
Interns

@Roseghost For now can you change it back to (Hope this is correct in the timeline) 

Neil Smyth

Board Member | Co-founder | CEO / CTO

Avatar
René Honig

Board Member | Co-founder | Chief Strategy & Innovation

Avatar
Valentin Yanakiev

Engineering Lead

Avatar
Evgeni Dimitrov

Quality Assurance Lead

Avatar
Merijn Zondag

Sustainability & Fundraising

Avatar
Svetoslav Petkov

Developer

Avatar
Kaylee Scholtes

UX/UI Intern

Avatar
Rosalie Swarte

UX/UI Intern

Avatar
Lazar Tasic

Graphic Design**

Avatar
Fintan Smyth

Communications Advisor** [Vanesti Ventures]

Avatar
Denise Larsson

Innovation Analyst


Avatar
Andrew Pazniak

Senior Developer

Avatar
Aleksandar Stojanović

Full stack developer

Avatar
Simone Rietmeijer

User Centric Design

Avatar
Birgit Ros

Communications Lead

Avatar
Carlos Cano de Santayana

Full stack developer

Avatar
Mayte Ragni

Innovation Analyst

Avatar 
Senna Sjambar

Data Analytics Intern

**Comment by techsmyth** [comment]
Key driver is to present a lack of hierarchy,.

Note that we do also need to put up an entry for Senna - probably a good idea to track that separately but if easier take along here...title is Data Analytics Intern.

**Comment by BirgitAlkemio** [comment]
@techsmyth Senna is allready on!

**Review by BirgitAlkemio — APPROVED** [review]

**Pull request merged**
