### PR TITLE
Carousel of partner logos

### PR DESCRIPTION
**Pull request by techsmyth**
carousel is visible on: draft.alkem.io

Note: logos are poor quality, and no way to trigger the switch: https://github.com/alkem-io/website/issues/204

### CODE REVIEW

**Comment by Fintokyo** [comment]
Looks good; suggest to make the KVK logo a bit smaller; and to make sure that all the logos are center aligned vertically

**Comment by Fintokyo** [comment]
And to make the Ministrie logo a bit bigger, as hard to read the words

**Comment by Fintokyo** [comment]
By adding this logo carousel, the top and bottom of the main image are no longer visible

**Comment by techsmyth** [comment]
Surprised that the image is getting cropped more due to this change. Ideally we solve this structurally with the fix pending related to using fixed width images (@Roseghost any update on that?).

Re kvk logo, I have just pushed up a change that makes this smaller. 
Re Min BZK logo, I would love to have a vector image version of this but do not have that. I have asked them directly. For now this is the best we can do :(

Key question is whether to go for this into prod now or wait for the updates?

**Comment by Fintokyo** [comment]
The KVK logo looks good now. Some of the other logos don't seem to be centre aligned (vertically), in case it is easy to fix that. 
It seems the image is only getting cropped on the desktop version, as it looks really good on the mobile phone and iPad versions. On that basis I'd go ahead and put it into prod now, and then try to fix the desktop version image this week. FYI on the desktop version the main issue with the cropping is that you can't see the blue part of the Ukraine flag, you can only see the yellow part.

**Comment by Fintokyo** [comment]
Btw in the carousel, before the NGI logo, consider if you want to put "Partners:", so that it is clear what role these entities have in Alkemio, and that people don't think that these 7 companies are the only customers of Alkemio

**Comment by Fintokyo** [comment]
I was playing around with the size of the window on my desktop, and when I make the window small the image is fine, but when it is normal size it is cropped, FYI

**Pull request merged**
