### PR TITLE
as per issue #354 - Missing analytics! 

### PR DESCRIPTION
**Pull request by Roseghost**
Issue #354 but missing an analytics link. For the rest the alignment of button is different than on design. There are no clear rules for site and this might breakdesign

### Governance 

- [ ] Documentation is added
- [x] Test cases are added or updated by netlify

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Comment by BirgitAlkemio** [comment]
@Roseghost Looks good to me. @techsmyth Please have a look before we put it up. Let's run it as a test for 2 weeks.

**Comment by BirgitAlkemio** [comment]
Hi Rosa, hierbij de  link met url tracker naar hubspot. 
https://www.linkedin.com/company/alkemio-foundation/jobs/?utm_campaign=Alkemio%20general&utm_source=LI&utm_medium=website&utm_term=ctahome

**Review by BirgitAlkemio — COMMENTED** [review]
Hi Rosa, hierbij de  link met url tracker naar hubspot. 
https://www.linkedin.com/company/alkemio-foundation/jobs/?utm_campaign=Alkemio%20general&utm_source=LI&utm_medium=website&utm_term=ctahome

**Review by techsmyth — CHANGES_REQUESTED** [review]
Hi Rosa, 

what is the rational with doing the Navbar this way? It looks like a maintenance nightmare...suggest we chat it through re alternatives.

Cheers, Neil

**Review by BirgitAlkemio — COMMENTED** [review]
Hi, I see now that Valentin has closed the application. Need to check with him, before putting up the link. 
image

**Pull request merged**
