### PR TITLE
added news top level menu entry

### PR DESCRIPTION
**Pull request by techsmyth**
To merge after discussion with Fintan

### CODE REVIEW

**Comment by Fintokyo** [comment]
Hi Birgit, Neil,

I agree it is good to add 'news' into the top menu bar, between 'Partners' and 'About'. 

For the quick fix, instead of having it link to the Blogs page, I would have it link to the bottom of the page where we have the various news links (LinkedIn, Twitter, Blogs, Newsletter). Then the users can see that Alkemio has multiple types of news items and they can go to their preferred choice.

On a separate but related point, on the 'Releases' page, I would change the format to be more similar to the 'Newsletters' page, whereby you only include links to the different publications instead of including the full text of the latest publication. Currently on the Releases page you have to scroll down a lot before you get to either (i) the links to the previous publications or (ii) the 'sign-up for releases' prompt

Thanks,
Fintan

**Comment by techsmyth** [comment]
@Fintokyo @BirgitAlkemio in talking with Fintan the conclusion is to create a simple news page for now with an overview of how to keep in contact with what is happening in the wider Alkemio context. This PR has been updated to add a simple page. There are some additional refinements needed but suggest to take those into another PR...

**Comment by Fintokyo** [comment]
One other addition at this stage, if easy to do, is to add to the news page an 'Alkemio in the news' section, with links to articles (such as the recent BVK article/interview)

**Review by BirgitAlkemio — APPROVED** [review]
-Changed the title into newsroom (lets get this page on now and get more brainpower and interactions into the second iteration).  
-Deleted the reference to the social media platforms, Git hub might not be in that space and a clean summup will do the trick for most people without the differentation. It has a lot of double information, incl the footer links to Github, LI and Twitter. 
-Added a cta to subscribe for the newsletter (to grow and track to our community).

**Pull request merged**
